version: '3'
networks:
  internal: {}
services:
  web:
    build: ./
    image: jorgelig/tastyigniter:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - internal
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tastyigniter
      MYSQL_USER: tastyigniter
      MYSQL_PASSWORD: tastyigniter
      MYSQL_ROOT_PASSWORD: tastyigniter
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
  redis:
    image: redis:6
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: always
    networks:
      - internal
volumes:
  db_data:
